### ISSUE TITLE
Screenshots Hasil

### ISSUE THREAD

**Issue by velyacahaya** [asistensi-matematika/tugas2-pbo-velyacahaya#1]
![Screenshot (62)](https://user-images.githubusercontent.com/55883852/66186983-e78cb600-e6ad-11e9-94aa-15bc8b5851b2.png)
![Screenshot (63)](https://user-images.githubusercontent.com/55883852/66186985-e8254c80-e6ad-11e9-9367-25fbc3b5742d.png)

**Comment by svmihar** [comment]
mbak ini seharusnya di masukkan ke dalam sini 

https://github.com/asistensi-matematika/tugas2-pbo-velyacahaya/blob/master/tugas_a.md#screenshot-hasil
